### ISSUE TITLE
Is this package dead?

### ISSUE THREAD

**Issue by lschaupp** [supabase/realtime-py#67]
I would love to use realtime-py for some app backend - but based on the number of commits in the past few months,
I am wondering if this project is dead?

**Comment by silentworks** [comment]
This project isn't dead. Sorry we have been absent from it for so long, we are now putting more time into our Python libraries and looking to get them on par with our JavaScript libraries.

**Comment by MindsightsAI** [comment]
@silentworks can you help with solution for broadcast and https://github.com/supabase-community/realtime-py/issues/39 ?

**Comment by bitnom** [comment]
> This project isn't dead. Sorry we have been absent from it for so long, we are now putting more time into our Python libraries and looking to get them on par with our JavaScript libraries.

I got this working: https://github.com/bitnom/aiorealtime in-case it's of any interest. Don't expect best practices everywhere. I'm in a hurry with something at the moment.

**Comment by silentworks** [comment]
The latest version `2.0.2` is a working version of this library.
